export const GET_USER_INFO_REQUEST = 'PROFILE_GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'PROFILE_GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'PROFILE_GET_USER_INFO_ERROR';

export const GET_USER_SETTINGS_REQUEST = 'PROFILE_GET_USER_SETTINGS_REQUEST';
export const GET_USER_SETTINGS_SUCCESS = 'PROFILE_GET_USER_SETTINGS_SUCCESS';
export const GET_USER_SETTINGS_ERROR = 'PROFILE_GET_USER_SETTINGS_ERROR';

export const UPDATE_USER_INFO_REQUEST = 'PROFILE_UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_SUCCESS = 'PROFILE_UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_ERROR = 'PROFILE_UPDATE_USER_INFO_ERROR';
export const UPDATE_USER_INFO_VALIDATION_ERROR = 'PROFILE_UPDATE_USER_INFO_VALIDATION_ERROR';

export const UPLOAD_USER_LOGO_REQUEST = 'PROFILE_UPLOAD_USER_LOGO_REQUEST';
export const UPLOAD_USER_LOGO_SUCCESS = 'PROFILE_UPLOAD_USER_LOGO_SUCCESS';
export const UPLOAD_USER_LOGO_ERROR = 'PROFILE_UPLOAD_USER_LOGO_ERROR';

export const DELETE_USER_LOGO_REQUEST = 'PROFILE_DELETE_USER_LOGO_REQUEST';
export const DELETE_USER_LOGO_SUCCESS = 'PROFILE_DELETE_USER_LOGO_SUCCESS';
export const DELETE_USER_LOGO_ERROR = 'PROFILE_DELETE_USER_LOGO_ERROR';
